### ISSUE TITLE
希望能关联实现类注入

### ISSUE THREAD

**Issue by SealinRepo** [kings1990/bean-assistant-doc#2]
当前版本1.0.2，直接输入Service接口是没有自动注入的，要是能关联到实现类上有指定注解的情况支持自动生成实现类bean注入就好了，bean字段名称应该用子类名。
例如我在输入IUserService，能关联引入UserServiceImpl。

**Comment by kings1990** [comment]
有点奇怪，不应该都是注入接口吗？你咋注入的是实现类？如果是实现类，你需要输入实现类的关键字

**Comment by kings1990** [comment]
我懂了，你应该是这种场景
Controller依赖 xxService 的 lib，xxService 依赖 xxServiceImpl，现在在Controller中需要使用xxService，但是没有直接依赖 impl 的 lib 导致没加载出来。

这个问题我将在今天 1.0.3 修复

**Comment by kings1990** [comment]
Fix version download [https://plugins.jetbrains.com/plugin/24576-bean-assistant/versions/stable/555556](https://plugins.jetbrains.com/plugin/24576-bean-assistant/versions/stable/555556)
