### ISSUE TITLE
测试类中支持@Mock

### ISSUE THREAD

**Issue by spinachs** [kings1990/bean-assistant-doc#3]
你好，希望能够在测试类中自动生成@Mock的变量，非常感谢。

**Comment by kings1990** [comment]
可以具体提供一下代码以及写法吗？包所在的位置截图，目前不支持在 test 目录下的扫描

**Comment by spinachs** [comment]
功能类
@Service
public class ProductService {
    @Resource
    private SkuService skuService;
}

@Service
public class SkuService {
}
测试类
public class ProductServiceTest {
    **@Resource 自动生成
    @Mock        期望生成**
    private SkuService skuService;
    @InjectMocks
    @Spy
    private ProductService productService;
}

**Comment by kings1990** [comment]
感觉不行，目前是支持配置注解的（看下图）。但是这个配置会作用在全局下（即要么在非测试类也会加上`@mock`注解），如果做了区分，那么配置将变得复杂。而这不是一种常规的解决方案。建议使用 live template 来处理该类场景

<img width="832" alt="image" src="https://github.com/kings1990/bean-assistant-doc/assets/8969637/3b307dd6-cc21-4835-9b8e-f0f62f0b07b5">
